# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.cache/wt [current_project]
set_property parent.project_path /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths {
  /home/computador
  /home/computador/Downloads/esrg-v-verilog
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/adder.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/alu.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/aludec.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/controller.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/datapath.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/esrg-v-verilog/esrg-v-verilog/devices/devices.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/esrg-v-verilog/esrg-v-verilog/dmem/src/dmem.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/extend.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/flopr.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/hazardunit.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/esrg-v-verilog/esrg-v-verilog/imem/src/imem.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/maindec.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/mux2.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/mux3.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/mux4.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/mux5.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/mux8.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/pipelineregD.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/pipelineregE.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/pipelineregM.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/pipelineregW.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/regfile.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/src/riscvsingle.v
  /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/sources_1/imports/esrg-v-verilog/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/constrs_1/new/IO.xdc
set_property used_in_implementation false [get_files /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/constrs_1/new/IO.xdc]

read_xdc /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/computador/Desktop/Xilinx/RISCV_PIPELINE/RISCV_PIPELINE.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
